<?php

declare(strict_types=1);

/**
 * Build client/js/cpu_policy.json from ranked replays (SQLite) or fixture JSON.
 *
 *   php scripts/cpu_policy_harvest.php --db=/path/to/tcg.db
 *   php scripts/cpu_policy_harvest.php --fixtures=tests/fixtures/cpu_policy
 *
 * Writes an aggregated artifact only (card rates, no Discord ids / names / rooms).
 */

require_once dirname(__DIR__) . '/src/Game/CpuPolicy.php';

$root = dirname(__DIR__);
$outJson = $root . '/client/js/cpu_policy.json';
$outJs = $root . '/client/js/cpu-policy-data.js';

$dbPath = null;
$fixtureDir = null;
foreach ($argv as $arg) {
    if (str_starts_with($arg, '--db=')) {
        $dbPath = substr($arg, 5);
    } elseif (str_starts_with($arg, '--fixtures=')) {
        $fixtureDir = substr($arg, 11);
    }
}

$payloads = [];
if ($fixtureDir !== null && is_dir($fixtureDir)) {
    foreach (glob(rtrim($fixtureDir, '/\\') . '/*.json') ?: [] as $file) {
        $raw = file_get_contents($file);
        $data = $raw ? json_decode($raw, true) : null;
        if (is_array($data)) {
            $payloads[] = $data;
        }
    }
}

if ($dbPath !== null && is_file($dbPath)) {
    $payloads = array_merge($payloads, cpuPolicyLoadRankedPayloads($dbPath));
}

$result = CpuPolicy::aggregatePayloads($payloads);
$policy = $result['policy'];
$report = $result['report'];

$json = json_encode($policy, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
if ($json === false) {
    fwrite(STDERR, "encode failed\n");
    exit(1);
}
file_put_contents($outJson, $json . "\n");
$js = "/* Generated by scripts/cpu_policy_harvest.php — do not edit. */\n"
    . "window.LLTCG_CPU_POLICY = " . $json . ";\n";
file_put_contents($outJs, $js);

fwrite(STDOUT, "replays=" . ($policy['corpus']['replays'] ?? 0)
    . " held_out=" . ($policy['corpus']['held_out'] ?? 0)
    . " live_set_agreement=" . json_encode($report['live_set_agreement'] ?? null)
    . " clearable_commit_agreement=" . json_encode($report['clearable_commit_agreement'] ?? null)
    . "\n");
fwrite(STDOUT, "wrote $outJson\n");

/**
 * @return list<array<string,mixed>>
 */
function cpuPolicyLoadRankedPayloads(string $dbPath): array
{
    if (!class_exists('PDO')) {
        fwrite(STDERR, "PDO required to read $dbPath\n");
        return [];
    }
    $db = new PDO('sqlite:' . $dbPath, null, null, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
    $top = $db->query(
        "SELECT discord_id FROM tcg_rank
         WHERE game_mode = 'standard' AND games >= " . CpuPolicy::RANK_MIN_GAMES . "
           AND rating >= " . CpuPolicy::RANK_FLOOR . "
         ORDER BY rating DESC, wins DESC
         LIMIT 50"
    );
    $ids = $top ? $top->fetchAll(PDO::FETCH_COLUMN) : [];
    if (!$ids) {
        fwrite(STDERR, "no ranked accounts at floor in $dbPath\n");
        return [];
    }
    $out = [];
    $stmt = $db->prepare('SELECT payload_json, room_id FROM tcg_replays WHERE discord_id = ?');
    $rankStmt = $db->prepare('SELECT 1 FROM tcg_ranked_matches WHERE room_id = ? LIMIT 1');
    foreach ($ids as $uid) {
        $stmt->execute([(string)$uid]);
        while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
            $room = (string)($row['room_id'] ?? '');
            $rankStmt->execute([$room]);
            if (!$rankStmt->fetchColumn()) {
                continue;
            }
            try {
                $payload = replayPayloadDecodeFromStorageLocal((string)($row['payload_json'] ?? ''));
            } catch (Throwable $e) {
                continue;
            }
            if (CpuPolicy::payloadIsCpu($payload)) {
                continue;
            }
            $out[] = $payload;
        }
    }
    fwrite(STDERR, 'loaded ' . count($out) . " ranked payloads from db\n");
    return $out;
}

/** @return array<string,mixed> */
function replayPayloadDecodeFromStorageLocal(string $raw): array
{
    $raw = trim($raw);
    if (str_starts_with($raw, 'LLTCG_GZ1:')) {
        $gz = base64_decode(substr($raw, strlen('LLTCG_GZ1:')), true);
        if ($gz === false) {
            throw new RuntimeException('bad gzip');
        }
        $json = gzuncompress($gz);
        if ($json === false) {
            throw new RuntimeException('bad gzip');
        }
        $payload = json_decode($json, true);
    } else {
        $payload = json_decode($raw, true);
    }
    if (!is_array($payload)) {
        throw new RuntimeException('bad payload');
    }
    return $payload;
}
