#!/usr/bin/env python3
"""Apply curated Simplified Chinese copy for hub / menus / lobby / options."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ZH_PATH = ROOT / "locales" / "zh.json"

# Menu-facing namespaces + shared nav terms. Prefer TCG vocabulary over MT.
OVERRIDES: dict = {
    "logo": {
        "tagline": "非官方网页版",
    },
    "news": {
        "label": "新闻",
        "title": "新闻",
        "close": "关闭",
        "backToList": "← 全部新闻",
        "empty": "暂无新闻。",
        "untitled": "无标题",
        "cardUnknown": "未找到卡牌：{id}",
        "newBadge": "新！",
    },
    "auth": {
        "checking": "正在检查 Discord 登录…",
        "signingIn": "正在登录…",
        "signInDiscord": "使用 Discord 登录",
        "guestPrompt": "使用 Discord 登录以保存收藏并参加排名对战。",
        "guestPlayHint": "无需账号即可游玩非排名对战，或登录后参加排名对战。",
        "sessionExpired": "会话已过期 — 请重新登录，或继续游玩非排名对战。",
        "loadError": "无法加载账号 — 你仍可游玩非排名对战。",
        "guestTimeout": "登录检查超时 — 可先游玩非排名对战，或重试 Discord 登录。",
    },
    "menu": {
        "unrankedPlay": "非排名对战",
        "unrankedSub": "开房、与好友对战，或练习对战 CPU",
        "deckExperiment": "牌组实验",
        "deckExperimentSub": "用全部卡牌构筑——仅限访客，不计入排名",
        "howToPlay": "怎么玩",
        "howToPlaySub": "与香音一起的新手实战教学",
    },
    "hub": {
        "signedIn": "已登录",
        "signedInAs": "已登录",
        "signedInAsHtml": "以 <b>{name}</b> 登录",
        "dailyBoosters": "每日补充包：今日剩余 {remaining} / {limit}（JST）",
        "dailyWelcomeBonus": "（欢迎奖励！）",
        "daily": "每日补充包：今日剩余 {remaining} / {limit}（JST）",
        "dailyBonus": "（欢迎奖励！）",
        "rankLine": "ELO {elo} · {wins}胜-{losses}负 · 胜率 {winPct}%",
        "options": "选项",
        "signOut": "退出登录",
        "openBoosters": "开启补充包",
        "openBoostersSub": "打开卡包",
        "deckBuilder": "牌组构筑",
        "deckBuilderSub": "编辑预设并设置排名牌组",
        "rankedPvp": "排名对战",
        "rankedPvpSub": "匹配对战并提升 ELO",
        "leaderboard": "排行榜",
        "leaderboardSub": "查看在线排名",
        "unranked": "非排名对战",
        "unrankedSub": "开房、好友对战、CPU 练习",
        "tournamentMode": "锦标赛模式",
        "tournamentModeSub": "即将推出",
        "howToPlay": "怎么玩",
        "howToPlaySub": "与香音一起的新手实战教学",
        "backHub": "← 主页",
        "missions": "任务",
        "rankedPrCount": "{remaining} / {limit}",
        "rankedPrTitle": "今日剩余排名 PR 奖励：{remaining} / {limit}（JST）",
    },
    "lobby": {
        "title": "非排名对战",
        "yourName": "你的名字",
        "namePlaceholder": "偶像名字…",
        "deck": "牌组",
        "createRoom": "创建房间",
        "joinRoom": "加入房间",
        "roomCode": "房间代码",
        "vsPlayer": "对战玩家",
        "vsCpu": "对战 CPU",
        "practiceCpu": "练习对战 CPU",
        "cpuDifficulty": "CPU 难度",
        "cpuEasy": "简单 — 随机入门牌组",
        "cpuNormal": "普通 — 更聪明的技能与 LIVE",
        "cpuHard": "困难 — 强力牌组与技能优先",
        "cpuExpert": "专家 — 模拟搜索与威胁预判",
        "findRandomMatch": "随机匹配",
        "spectate": "观战",
        "cancelSearch": "取消搜索",
        "phaseTimer": "阶段计时（主要阶段与 LIVE）",
        "phaseTimerSec": "每阶段秒数（10–120）",
        "backHub": "← 主页",
        "orJoinFriend": "或加入好友",
        "orMatchRandomly": "或随机匹配",
        "casualHint": "休闲对战 — 不计 ELO 与排名战绩",
        "experimentDeckPassword": "实验牌组密码",
        "experimentPasswordPlaceholder": "8 位代码",
        "experimentDeckBtn": "牌组实验",
        "experimentDeckHint": "在「牌组实验」中构筑并生成密码，然后粘贴到这里 — 或从下方选择已保存的牌组。",
        "secondsLabel": "{n} 秒",
        "casualQueueStats": "{waiting} 人等待 · {inGame} 场休闲对战中",
        "casualSearching": "正在寻找对手…（{seconds} 秒）",
        "roomCodePlaceholder": "ABCD1234",
    },
    "deck": {
        "title": "牌组构筑",
        "experimentTitle": "牌组实验",
        "deckName": "牌组名称",
        "presetSlot": "预设槽位（最多 10 个）",
        "search": "搜索卡牌",
        "searchPlaceholder": "名称、ID 或规则文本…",
        "collection": "收藏",
        "currentDeck": "当前牌组",
        "savePreset": "保存预设",
        "equipRanked": "设为排名牌组",
        "autoBuild": "自动构筑",
        "clear": "清空",
        "hint": "根据收藏自动优化构筑 · 点击添加/移除 · 悬停预览 · 点数合计须 ≤ 9",
        "hoverEmpty": "将鼠标悬停在牌组卡牌上即可在此预览。",
        "backHub": "← 主页",
        "backMenu": "← 菜单",
        "deckPassword": "牌组密码",
        "deckPasswordPlaceholder": "输入密码以加载",
        "load": "加载",
        "savedPassword": "已保存密码：",
        "copy": "复制",
        "cardPool": "卡池",
        "resetStarter": "重置入门牌组",
        "useStarter": "使用入门牌组",
        "randomDeck": "随机牌组",
        "updateSavedDeck": "更新已保存牌组",
        "generatePassword": "生成密码",
        "experimentHint": "完整卡池 · 构筑合法牌组后可生成密码 · 点数合计须 ≤ 9 · 长按或右键查看详情",
        "collectionOwned": "拥有卡牌总数 · {count}",
        "collectionLoading": "完整卡池 · 加载中…",
        "collectionMatch": "收藏 · {match} 条匹配",
        "deckStats": "合计 {total}/72 · 成员 {members}/48 · Live {lives}/12 · 能量 {energy}/12 · 点数 {lovecaPoints}/{lovecaLimit}",
        "lovecaPointLabel": "点数",
        "lovecaOverLimit": "点数合计将为 {total}（上限 {limit}）。",
        "lovecaDeckIllegal": "点数合计为 {total} — 牌组必须 ≤ {limit}。",
        "deckIllegalSize": "牌组必须合法：主牌组 60 张（成员 48、Live 12）与能量 12 张。",
        "lovecaExplain": "部分强力卡消耗点数。主牌组点数合计须保持在 9 或以下（每张副本都计入）。",
        "deckEmpty": "从收藏中点击卡牌来构筑牌组。",
        "deckEmptyExperiment": "从卡池中点击卡牌，构筑合法的 60+12 牌组。",
        "experimentStarterTitle": "选择入门牌组",
        "experimentStarterLead": "加载官方入门列表作为基础 — 可从完整卡池自由编辑。",
        "accountStarterHint": "你的账号入门牌组：{starter} · 预设 #1 从该列表开始。",
        "noStarterOnAccount": "此账号尚无入门牌组。",
        "loadedStarterIntoPreset": "已将 {name} 加载到预设 #{slot}。",
        "loadedStarterFallbackName": "入门牌组",
        "chooseStarterFirst": "请先选择入门牌组。",
        "building": "构筑中…",
        "autoBuiltSuccess": "已根据收藏自动构筑合法牌组。",
        "starterDecksNotLoaded": "入门牌组尚未加载。",
        "equippedRanked": "已设为排名牌组。",
        "basicDecks": "基础牌组",
        "filters": {
            "title": "筛选",
            "showAdvanced": "显示高级筛选",
            "hideAdvanced": "隐藏高级筛选",
            "all": "全部",
            "allTypes": "全部类型",
            "allFields": "全部字段",
            "allProducts": "全部产品",
            "allSets": "全部系列",
            "any": "任意",
            "min": "最低",
            "max": "最高",
            "notIncluded": "不包含",
            "heartAll": "全部",
            "drawIcon": "抽卡图标",
            "scoreIcon": "得分图标",
            "label": {
                "type": "类型",
                "group": "团体",
                "rarity": "稀有度",
                "keywordIn": "关键字",
                "product": "产品",
                "productSet": "产品系列",
                "subunit": "小组",
                "parallel": "异画",
                "printedHearts": "印刷心形",
                "requiredHearts": "所需心形",
                "bladeHearts": "刀锋心形",
                "blade": "刀锋",
                "cost": "费用",
                "score": "得分",
            },
            "type": {
                "member": "成员",
                "live": "LIVE",
                "energy": "能量",
            },
            "searchMode": {
                "all": "全部字段",
                "name": "名称",
                "text": "文本",
                "id": "卡号",
            },
            "searchPlaceholder": {
                "all": "名称、ID 或规则文本…",
                "name": "卡名…",
                "text": "规则文本…",
                "id": "卡号，例如 PL!N-sd1-021-SD",
            },
            "productKind": {
                "bp": "补充包",
                "pb": "高级补充包",
                "pb_duo": "高级补充包（DUO）",
                "sd": "入门牌组",
                "collection": "收藏",
                "pr": "PR",
            },
            "parallel": {
                "normal": "仅普通",
                "parallel": "仅异画",
            },
            "groups": {
                "mus": "μ's",
                "nijigasaki": "虹咲学园",
                "sunshine": "Aqours",
                "superstar": "Liella!",
                "hasunosora": "莲之空",
                "saintsnow": "Saint Snow",
                "arise": "ARISE",
                "sunnypassion": "Sunny Passion",
            },
            "sort": {
                "aria": "收藏排序与顺序",
                "sortBy": "排序方式",
                "order": "顺序",
                "asc": "升序",
                "desc": "降序",
                "id": "卡号",
                "rarity": "稀有度",
                "name": "名称（偶像）",
                "type": "卡牌类型",
                "group": "团体/学校",
                "recent": "最近获得",
            },
        },
        "starters": {
            "nijigasaki": "虹咲学园入门牌组",
            "muse": "μ's 入门牌组",
            "liella": "Liella! 入门牌组",
            "hasunosora": "莲之空入门牌组",
            "sunshine": "Aqours 入门牌组",
        },
        "groups": {
            "nijigasaki": "虹咲学园",
            "hasunosora": "莲之空",
            "sunshine": "Aqours",
            "superstar": "Liella!",
            "mus": "μ's",
            "saintsnow": "Saint Snow",
            "arise": "ARISE",
            "sunnypassion": "Sunny Passion",
        },
    },
    "booster": {
        "title": "开启补充包",
        "openPack": "打开卡包（{n} 张卡）",
        "openPaidBox": "打开 1 盒（{n} 包）",
        "ratesLead": "池中 {pool} 张卡 · 有机会出现在 {n} 张卡的卡包中",
        "packOpened": "卡包已打开",
        "godPack": "神包！",
        "openAnother": "再开一包",
        "openSameAgain": "再开同样的包",
        "packsLeft": "今日剩余 {n} 包（JST）",
        "mainMenu": "主菜单",
        "backHub": "← 主页",
        "noDailyPacks": "今日免费卡包已用完",
        "paidLead": "花费星宝石以继续今日开包。",
        "openOnePack": "打开 1 包",
        "starGemsLabel": "星宝石：",
        "starGemsUnit": "{n} 星宝石",
        "dailyPack": "每日卡包",
        "packRatesTitle": "卡包概率",
        "packRatesPerPack": "每包 · 点击卡牌查看详情",
        "ratesLoading": "正在加载概率…",
        "duplicatesConverted": "重复卡已转换",
        "migrationText": "成员/Live 每张超过 4 张、能量每张超过 12 张的多余副本将转换为 {gems}。",
        "convertedToGems": "· 已转换为 {n} 星宝石",
        "needMoreGems": "还需要 {n} 星宝石才能开盒",
        "noPacksOrGems": "今日免费卡包已用完，星宝石也不够。",
        "openBox": "打开盒装（{n} 包）",
        "selectBoxFirst": "请先选择补充包系列",
    },
    "ranked": {
        "title": "排名对战",
        "findMatch": "寻找对战",
        "cancelSearch": "取消搜索",
        "spectate": "观战",
        "timerNote": "主要阶段与 LIVE 阶段使用 120 秒计时。",
        "deckLabel": "排名牌组",
        "matchSound": "匹配成功时播放提示音",
        "leaderboard": "排行榜",
        "leaderboardTitle": "排行榜",
        "backHub": "← 主页",
        "infoLine": "ELO {elo} · {record}",
        "record": "{wins}胜-{losses}负 · 胜率 {winPct}%",
        "recordFull": "{wins}胜-{losses}负 · 胜率 {winPct}% · 负率 {lossPct}%",
        "queueStats": "{waiting} 人等待 · {inGame} 场排名对战中",
        "searching": "搜索中…（{seconds} 秒）",
        "readySearch": "准备搜索",
        "prRemaining": "今日 PR 奖励：剩余 {remaining} / {limit}（JST）",
    },
    "leaderboard": {
        "title": "排行榜",
        "lead": "排名对战的最高 ELO。可为个人资料行设置卡牌横幅与旗帜。",
        "empty": "尚无排名对战记录 — 参加排名对战后会出现在这里。",
        "editBanner": "编辑个人资料",
        "eloSuffix": "ELO",
        "eloLabel": "{elo} ELO",
        "profileBanner": "个人资料横幅",
        "bannerLead": "选择一张你拥有的卡牌，然后上下拖动裁切区，选定排行榜上展示的立绘。",
        "bannerSearchPlaceholder": "按卡名搜索…",
        "bannerNoMatch": "没有符合搜索的卡牌。",
        "bannerPreview": "预览",
        "saveBanner": "保存横幅",
        "profileFlag": "个人资料旗帜",
        "flagLead": "选择一面旗帜，显示在排行榜名字旁。",
        "flagSearchPlaceholder": "搜索旗帜…",
        "equipFlag": "装备旗帜",
        "flagNone": "无",
        "flagEquipped": "当前已装备。",
        "flagReady": "要装备 {name} 吗？",
        "flagLoading": "正在加载旗帜…",
        "selectCardFirst": "请先选择一张卡",
        "jumpToYou": "跳到我的名次",
        "yourRank": "你的排名：#{rank}",
    },
    "options": {
        "title": "选项",
        "enhancedTextures": "高稀有度卡牌的增强纹理",
        "soundEffects": "音效",
        "sfxVolume": "音效音量",
        "stuckTitle": "对战卡住了？",
        "stuckLead": "若排名对战把你重连到已损坏或已结束的对局，可在此离开该对战记录。若对局仍在进行中，将计为弃权。",
        "resetTitle": "重置账号",
        "resetLead": "删除全部收藏卡牌、牌组预设、排名战绩与补充包进度。你将重新选择入门牌组。此操作无法撤销。",
        "resetAccount": "重置账号",
        "leaveActive": "离开当前对战",
        "backHub": "← 主页",
    },
    "starter": {
        "title": "选择入门牌组",
        "lead": "选择一套官方入门牌组作为收藏基础。此选择不可更改。",
        "confirm": "确认入门牌组",
    },
    "waiting": {
        "roomCreated": "房间已创建！",
        "shareCode": "把此代码分享给对手：",
        "tapCopy": "点击复制 📋",
        "clickCopy": "点击复制",
        "waitingOpponent": "正在等待对手加入…",
        "cancel": "取消",
        "phaseTimerInfo": "阶段计时：每个主要阶段与 LIVE 阶段 {sec} 秒",
    },
    "stamps": {
        "audio": "贴纸语音",
        "audioMenu": "贴纸语音",
        "voiceVolume": "贴纸语音音量",
        "cooldown": "稍等…",
        "done": "完成",
        "editProfile": "编辑喜爱贴纸",
        "empty": "没有贴纸。",
        "favoritesEmpty": "还没有收藏 — 请在「选项」中设置，或点击贴纸上的 ☆。",
        "pickerTitle": "发送贴纸",
        "profileCount": "已选择 {n} / {max}",
        "profileFull": "最多只能保存 {max} 张喜爱贴纸。",
        "profileHint": "在对战中发送贴纸时，这些会出现在 ★ 收藏 页签中。",
        "profileHintEmpty": "可选 — 最多选择 20 张贴纸，便于对战中快速使用。",
        "profilePickLead": "点击贴纸以添加或移除（最多 20）。对战中在 ★ 收藏 页签使用。",
        "profilePickTitle": "喜爱贴纸",
        "profileSection": "喜爱贴纸",
        "send": "💬 贴纸",
        "tabEn": "English",
        "tabFavorites": "★ 收藏",
        "tabJa": "日本語",
    },
    "missions": {
        "claim": "领取",
        "claimedStarterToast": "已领取 {title} — 已解锁 {deck}",
        "claimedToast": "已领取 {title}（+{reward}）",
        "completeToast": "任务完成：{title}",
        "daily": {
            "completeAll": "完成全部每日任务",
            "openAllBoosters": "打开全部每日补充包",
            "rankedMatch": "参加一场排名对战",
            "useStamp": "在对战中使用贴纸",
        },
        "empty": "此页签没有任务。",
        "loading": "正在加载任务…",
        "milestone": {
            "cards1200": "拥有 1,200 张卡",
            "cards1600": "拥有 1,600 张卡",
            "cards400": "拥有 400 张卡",
            "cards800": "拥有 800 张卡",
            "profileBanner": "更新个人资料横幅",
            "profileFlag": "在个人资料上设置旗帜",
            "profileStamps": "设置喜爱贴纸",
            "ranked1": "进行 1 场排名对战",
            "ranked10": "进行 10 场排名对战",
            "ranked100": "进行 100 场排名对战",
            "ranked1000": "进行 1,000 场排名对战",
            "ranked5": "进行 5 场排名对战",
            "ranked50": "进行 50 场排名对战",
            "ranked500": "进行 500 场排名对战",
            "unranked1": "进行 1 场非排名对战",
            "winAqours": "使用仅含 Aqours 的主牌组获胜",
            "winHasunosora": "使用仅含莲之空的主牌组获胜",
            "winLiella": "使用仅含 Liella! 的主牌组获胜",
            "winMuse": "使用仅含 μ's 的主牌组获胜",
            "winNijigasaki": "使用仅含虹咲学园的主牌组获胜",
        },
        "rewardStarter": "选择入门牌组",
        "rewardStarterOwned": "已拥有",
        "starterPickCancel": "取消",
        "starterPickConfirm": "解锁入门牌组",
        "starterPickTitle": "选择入门牌组",
        "statusActive": "进行中",
        "statusClaimed": "已领取",
        "statusLocked": "未解锁",
        "statusReady": "可领取",
        "tabDaily": "每日",
        "tabMilestone": "里程碑",
        "title": "任务",
    },
    "ui": {
        "fullscreen": "全屏",
        "rankedSearch": "排名匹配",
        "casualSearch": "休闲匹配",
        "skipToResults": "跳到结果",
        "clickToOpen": "点击打开",
    },
    "spectate": {
        "listTitle": "观战",
        "listTitleRanked": "观看排名对战",
        "listTitleCasual": "观看非排名对战",
        "lead": "观看进行中的对战 — 仅观看，无法操作。",
        "barReadOnly": "观战 — 只读",
        "barNames": "观看 {p1} vs {p2}",
        "leave": "离开",
        "reconnected": "已重新连接观战。",
        "watch": "观看",
        "loading": "加载中…",
        "noMatches": "暂无可观看的对战。",
        "count": "观众：{n}",
        "matchEnded": "对战已结束 — 返回大厅。",
        "sessionEnded": "观战已结束。",
        "switchPerspective": "切换视角",
    },
    "replay": {
        "menuTitle": "录像查看器",
        "menuSubAuth": "加载已保存的对战录像并实时观看",
        "menuSubHub": "从你的库中观看已保存的对战录像",
        "title": "录像查看器",
        "back": "← 返回",
        "lead": "已结束的对战会自动保存到「最近」（最多 10 场）。手动保存的录像会永久保留在「已保存」——也可在此把「最近」的录像永久保存。",
        "refreshLibrary": "刷新库",
        "importLead": "有导出的录像文件？也可在此导入 JSON。",
        "fileLabel": "录像文件",
        "noFileSelected": "未选择文件。",
        "startImported": "开始导入的录像",
        "playPause": "播放/暂停",
        "positionAria": "录像进度",
        "handoffNote": "录像结束 — 现在由你操作。CPU 操控对手。",
        "exitReplay": "退出录像",
        "phaseBarHint": "录像 {step} / {total} — 用下方进度条逐步查看记录的操作。",
        "signInLibrary": "登录后可保存并查看库中的录像。",
        "emptyLibrary": "尚未保存录像。完成一场对战后选择保存录像。",
        "watch": "观看",
        "downloadJson": "下载 JSON",
        "loadingLibrary": "正在加载已保存的录像…",
        "loadLibraryFailed": "无法加载已保存的录像。",
        "win": "胜",
        "loss": "负",
        "replayLabel": "录像",
        "recentSection": "最近对战",
        "recentHint": "自动保存最近 10 场。最旧的会自动被替换。",
        "savedSection": "永久保存",
        "savedHint": "可从结果界面保存，或在此把「最近」中的录像永久保留。",
    },
}


def deep_merge(dst: dict, src: dict) -> dict:
    for k, v in src.items():
        if isinstance(v, dict) and isinstance(dst.get(k), dict):
            deep_merge(dst[k], v)
        else:
            dst[k] = v
    return dst


def scrub_global_mistranslations(obj):
    """Fix a few known MT footguns that still appear in menu-adjacent strings."""
    repl = (
        ("甲板", "牌组"),
        ("实验台", "实验牌组"),
        ("助推器", "补充包"),
        ("← 中心", "← 主页"),
        ("邮票", "贴纸"),
        ("图章", "贴纸"),
        ("印章", "贴纸"),
        ("候诊室", "待机室"),
    )
    if isinstance(obj, dict):
        return {k: scrub_global_mistranslations(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [scrub_global_mistranslations(x) for x in obj]
    if isinstance(obj, str):
        s = obj
        for a, b in repl:
            s = s.replace(a, b)
        return s
    return obj


def main() -> None:
    data = json.loads(ZH_PATH.read_text(encoding="utf-8"))
    # Replay: only patch menu-facing keys if present
    if "replay" in data and isinstance(data["replay"], dict):
        deep_merge(data["replay"], OVERRIDES.get("replay", {}))
    overrides = {k: v for k, v in OVERRIDES.items() if k != "replay"}
    deep_merge(data, overrides)
    # Light scrub on menu-facing namespaces only (avoid touching skill texts)
    for ns in (
        "logo",
        "news",
        "auth",
        "menu",
        "hub",
        "lobby",
        "deck",
        "booster",
        "ranked",
        "leaderboard",
        "options",
        "starter",
        "waiting",
        "stamps",
        "missions",
        "ui",
        "spectate",
        "replay",
        "splash",
        "win",
        "toast",
        "common",
        "mobile",
        "tutorialUi",
    ):
        if ns in data:
            data[ns] = scrub_global_mistranslations(data[ns])
    ZH_PATH.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"Updated {ZH_PATH}")


if __name__ == "__main__":
    main()
